import type { CounterlaneConfig } from "./types.js";

export const DEFAULT_CONFIG: CounterlaneConfig = {
  version: 1,
  dataDirectory: ".counterlane",
  codex: {
    command: "codex",
    args: ["app-server"],
    startupTimeoutMs: 15_000,
    requestTimeoutMs: 30_000,
    turnTimeoutMs: 30 * 60_000,
    shutdownTimeoutMs: 5_000,
    experimentalApi: false,
    approvalPolicy: "never",
    sandbox: {
      type: "workspaceWrite",
      networkAccess: false,
    },
    extraTurnParams: {},
  },
  routing: {
    profile: "balanced",
    static: {
      family: "sol",
      effort: "medium",
      speed: "standard",
    },
    familyMatchers: {
      luna: ["luna"],
      terra: ["terra"],
      sol: ["sol"],
    },
    candidateEfforts: ["low", "medium", "high", "xhigh", "max", "ultra"],
    prediction: {
      baselineDurationMs: 90_000,
      p90Multiplier: 1.6,
      minimumCalibrationSamples: 3,
      shrinkageSamples: 5,
      fallbackCreditsPerCostWeight: 8,
    },
    speed: {
      enabled: true,
      candidateTiers: ["standard", "fast"],
      defaultTier: "standard",
      allowUnadvertisedTiers: false,
      maxUsagePercentForPremium: 45,
      minimumLatencySensitivityForPremium: 0.38,
      profiles: {
        standard: {
          costMultiplier: 1,
          latencyMultiplier: 1,
          premium: false,
        },
        fast: {
          // Conservative fallback. Runtime model/list remains the authority for
          // availability, while these local estimates model economics.
          costMultiplier: 2.5,
          latencyMultiplier: 2 / 3,
          premium: true,
          modelOverrides: [
            { matcher: "gpt-5.4", costMultiplier: 2 },
            { matcher: "gpt-5.5", costMultiplier: 2.5 },
          ],
        },
      },
    },
    reservePercent: 20,
    enableMax: true,
    enableUltra: false,
    maxUsagePercentForMax: 45,
    maxUsagePercentForUltra: 30,
    minimumCompletion: {
      normal: 0.78,
      elevated: 0.9,
      critical: 0.97,
    },
    minimumQuality: {
      normal: 0.78,
      elevated: 0.9,
      critical: 0.97,
    },
    costModel: {
      inputCreditsPerMillionAtLuna: 25,
      cachedInputCreditsPerMillionAtLuna: 2.5,
      outputCreditsPerMillionAtLuna: 150,
      familyWeights: {
        luna: 1,
        terra: 2.5,
        sol: 5,
        unknown: 5,
      },
    },
    weights: {
      cost: 0.9,
      latency: 0.25,
      quota: 0.8,
      failure: 2.4,
      uncertainty: 0.7,
      switching: 0.1,
    },
  },
  meta: {
    enabled: true,
    minimumExactSamples: 4,
    minimumFallbackSamples: 8,
    maximumTwinSamplesPerContext: 24,
    confidenceZ: 1.645,
    upliftMargin: 0.5,
    priorStrength: 2,
    priorStandardDeviation: 25,
    expectedFutureSimilarTasks: 12,
    informationValueScale: 0.25,
    twinCostMultiplier: 1.1,
    maximumQuotaPressureForTwin: 0.62,
    maximumUsedPercentForTwin: 55,
    minimumCriticalVerifierStrength: 0.55,
  },
  twin: {
    execution: "parallel",
    preserveWorktrees: "on-failure",
    maximumDurationMs: 60 * 60_000,
    applyWinnerByDefault: false,
    requireOriginalStateUnchanged: true,
    worktreeBaseDirectory: null,
    dependencyDirectories: ["node_modules"],
    maximumDependencyFiles: 250_000,
    maximumDependencyBytes: 5_000_000_000,
  },
  verification: {
    autoDetect: true,
    routing: {
      enabled: true,
      candidateTiers: ["basic", "standard", "strong", "adversarial"],
      defaultTier: "standard",
      minimumTierByRisk: {
        normal: "basic",
        elevated: "standard",
        critical: "strong",
      },
      costWeights: {
        basic: 0.2,
        standard: 0.55,
        strong: 1.0,
        adversarial: 1.8,
      },
      detectionBoosts: {
        basic: 0.04,
        standard: 0.14,
        strong: 0.27,
        adversarial: 0.4,
      },
      detectionFloors: {
        basic: 0.35,
        standard: 0.6,
        strong: 0.9,
        adversarial: 0.97,
      },
      minimumIndependentChecks: {
        basic: 1,
        standard: 1,
        strong: 2,
        adversarial: 2,
      },
    },
    requireAtLeastOne: true,
    failOnNoVerifier: true,
    requireTaskSpecificCheck: false,
    defaultTimeoutMs: 10 * 60_000,
    maximumOutputBytes: 1_000_000,
    commands: [],
  },
  telemetry: {
    enabled: true,
    includePrompt: false,
    allowHostLedgerLearning: false,
    file: "events.jsonl",
    maximumReadEvents: 5_000,
    maximumReadBytes: 8_388_608,
  },
  utility: {
    verifiedSuccessValue: 100,
    verificationScoreValue: 10,
    normalizedCreditPenalty: 1,
    latencyPenaltyPerMinute: 0.2,
    failedTurnPenalty: 35,
    detectedVerificationFailurePenalty: 200,
    practicalEquivalenceMargin: 0.05,
  },
};
